# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "79ab71cfb3b44b2246570d49682e6779"
name = "sopfy-app"
handle = "sopfy-app"
application_url = "https://sold-jobs-quiz-meanwhile.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "100-ka-2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sold-jobs-quiz-meanwhile.trycloudflare.com/auth/callback",
  "https://sold-jobs-quiz-meanwhile.trycloudflare.com/auth/shopify/callback",
  "https://sold-jobs-quiz-meanwhile.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
